### ISSUE TITLE
Allow skipping certificate validation

### ISSUE THREAD

**Issue by psy-q** [matueranet/kanboard-import-trello#10]
It seems that the JSON-RPC client always tries to verify its peer, at least the way it's used right now. This makes it impossible to import into a Kanboard instance that has an invalid or self-signed certificate.

It should be possible to skip certificate validation during import, or to specify some additional valid certs so that the self-signed one can be supplied.

**Comment by danships** [comment]
I see skipping the SSL validation as a bad practice. Nowadays with letsencrypt it is fairly easy to get a valid SSL set up on a server. So I therefore do not see your suggestion as something that is desirable in this tool.

**Comment by psy-q** [comment]
The issue is that those servers where we run Kanboard can't freely contact Lets Encrypt, and they're on internal IPs anyway, which Let's Encrypt doesn't support (to the best of my knowledge). I agree that all servers should have valid certs, the only way for us to enforce this here would be to generate certs from our internal CA, and we wanted to avoid that.

**Comment by danships** [comment]
Looking at the json-rpc client code, it is possible to disable ssl verification. You can insert this line at the moment of [client initialization](https://github.com/matueranet/kanboard-import-trello/blob/master/import.php#L51) on your own fork of this repo:

```php
$client->withoutSslVerification();
```

See also [jsonRPCs HttpClient.php](https://github.com/fguillot/JsonRPC/blob/master/src/JsonRPC/HttpClient.php#L213)
