### ISSUE TITLE
Imported board has no users

### ISSUE THREAD

**Issue by kousu** [matueranet/kanboard-import-trello#13]
I ran your import script and it worked on the first try! There's a lot of fiddly bits and passwords to get in the right place but your instructions are very easy to follow and complete. That was awesome.

The imported board has no members, not even the "userId" member that I used to import comments, however, and so only my admin accounts seem to be able to see it. If I paste the address of the board (https://localhost/?controller=BoardViewController&action=show&project_id=2) in to a session with a non-admin user logged in, I get "Access Forbidden".

How do I bootstrap this board? Do I need to go edit the database by hand?

**Comment by kousu** [comment]
Er, I found the Permissions page (as my admin account), and added myself (and others) as a user. It would help to add a note about that to your otherwise very complete documentation!

**Comment by danships** [comment]
Thanks for your feedback, I've added an explanation to the readme.

**Comment by kousu** [comment]
Thank you! That will help people out in the future. Cheers.
