### ISSUE TITLE
/fguillot/json-rpc error

### ISSUE THREAD

**Issue by nmarus** [matueranet/kanboard-import-trello#2]
Getting the following error. I have triple verified all api keys/tokens. It seem there may be a update to /fguillot/json-rpc?

PHP Fatal error:  Uncaught exception 'JsonRPC\ConnectionFailureException' with message 'Unable to establish a connection' in /root/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php:309
Stack trace:
#0 /root/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(201): JsonRPC\Client->doRequest(Array)
#1 /root/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(137): JsonRPC\Client->execute('getAllProjects', Array)
#2 /root/kanboard-import-trello/import.php(58): JsonRPC\Client->__call('getAllProjects', Array)
#3 /root/kanboard-import-trello/import.php(58): JsonRPC\Client->getAllProjects()
#4 {main}

  thrown in /root/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php on line 309

**Comment by nmarus** [comment]
I was able to fix this by changing the composer.json to: 

{
    "require": {
        "fguillot/json-rpc": "v1.0.0"
    }
}

**Comment by danships** [comment]
Thanks for the feedback! I updated the json-rpc requirement in d71a1a6b04fa6dd4267504346187fc5aad92994d.

**Comment by nipasoni** [comment]
getting the following error when use getAllProjects() method
Uncaught JsonRPC\AccessDeniedException: Response: HTTP/1.0 401 Unauthorized in C:\xampp\htdocs\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php:301 Stack trace: #0 C:\xampp\htdocs\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(323): JsonRPC\Client->handleHttpErrors(Array) #1 C:\xampp\htdocs\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(201): JsonRPC\Client->doRequest(Array) #2 C:\xampp\htdocs\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php(137): JsonRPC\Client->execute('getVersion', Array) #3 C:\xampp\htdocs\kanboard\api1.php(9): JsonRPC\Client->__call('getVersion', Array) #4 {main} thrown in C:\xampp\htdocs\kanboard\vendor\fguillot\json-rpc\src\JsonRPC\Client.php on line 301

**Comment by hugopeek** [comment]
I'm having the same issue as nmarus, with json-rpc 1.0.0. I tried updating that dependency by running:

composer require fguillot/json-rpc @stable

But that didn't help.. The error:

```
PHP Notice:  date_default_timezone_set(): Timezone ID 'Etc/UTC
' is invalid in /var/www/html/vendor/kanboard-import-trello/util.php on line 31
PHP Warning:  fopen(http://localhost:8001/jsonrpc.php): failed to open stream: Connection refused in /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 249
PHP Fatal error:  Uncaught exception 'JsonRPC\Exception\ConnectionFailureException' with message 'Unable to establish a connection' in /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php:252
Stack trace:
#0 /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(191): JsonRPC\HttpClient->execute('{"jsonrpc":"2.0...')
#1 /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(176): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...')
#2 /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(126): JsonRPC\Client->execute('getAllProjects', Array)
#3 /var/www/html/vendor/kanboard-import-trello/import.php(58): JsonRPC\Client->__call('getAllProjects', Array)
#4 /var/www/html/vendor/kanboard-import-trello/import.php(58): JsonRPC\Client->getAllProjects()
#5 {main}
  thrown in /var/www/html/vendor/kanboard-import-trello/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 252
```

I'm running the command inside the vagrant box that comes with Kanboard. Will try to execute it from a different environment now to see what happens..
