### ISSUE TITLE
PHP Fatal error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by nmarus** [matueranet/kanboard-import-trello#3]
![trello](https://cloud.githubusercontent.com/assets/1557166/9500155/dbb20d2c-4bf1-11e5-9470-cfcdb8b1d3a5.png)
![import_kb](https://cloud.githubusercontent.com/assets/1557166/9500159/dea49a54-4bf1-11e5-8786-019c37e91c6c.png)

**Comment by nmarus** [comment]
Some more details after further debugging. It seems the import crashed after the third column when trying to download files. 

Downloading attachment for task XXXX to XXXX
PHP Fatal error:  Call to undefined function curl_init() in /root/kanboard-import-trello/import.php on line 219

I ended up commented out lines 212 - 243 and was able to get the import to happen successfully. Attachments were not that big of a deal. If you need any more details, let me know. Great script btw. Love it. :)

**Comment by danships** [comment]
Hi,

You indeed net the curl extension installed. I updated the composer.json to reflect that in commit d71a1a6b04fa6dd4267504346187fc5aad92994d.

**Comment by nnokoemmanuel** [comment]
Fatal error: Call to undefined function curl_init() in C:\wamp\www\nnokox\component\monetbil-php-master\monetbil.php on line 685

need help

**Comment by nnokoemmanuel** [comment]
ok guys i figured the answer
inother to enable  curl_init()  on your wamp server, do the following:

Enabling curl on WampServer.

If you are using the popular WampServer program on Windows, then you can try the following steps:

    Click on the WampServer icon in your system tray.
    Hover over the “PHP” option.
    Once the PHP menu appears, hover over the “PHP extensions” option.
    At this stage, a list of PHP extensions should appear. If an extension has a tick beside it, then it is already enabled. If the php_curl option does not have a tick beside it, then it is not enabled. To enable curl, simply click on the php_curl option.
    WampServer should automatically restart Apache and the changes should take effect.
    If WampServer does not automatically restart Apache, then you can manually force it to do so by clicking on the “Restart All Services” option in the main menu.

Hopefully, this guide helped you to get rid of that nasty “undefined function curl_init” error!
