### ISSUE TITLE
autoload.php error

### ISSUE THREAD

**Issue by tloehr** [matueranet/kanboard-import-trello#5]
Hi,

when I try to run the import.php script it stops with the following error message:

`PHP Fatal error:  require_once(): Failed opening required '/root/kanboard-import-trello-master/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /root/kanboard-import-trello-master/import.php on line 2`

What am I doing wrong ?

Bye, Torsten...

**Comment by danships** [comment]
The script uses composer to load its dependencies. You first need to execute `composer install` to load the dependencies and create the autoload.php file.

**Comment by tloehr** [comment]
Ok. Did the trick. Thanks.
