### ISSUE TITLE
If kanboard is on a commercial host

### ISSUE THREAD

**Issue by hauserulrich** [matueranet/kanboard-import-trello#6]
Hello,

I tried to migrate the tool to be used with a commercially managed host. I can pass php-code to there, but can only call it via the browser. So I modified the code to use $_GET (See code at the end). According to my tracing it all works well up to the point where the RCP comes into play (After line 88 of the amended code). And if I look at the RPC, it doesn't fit what is given in the description (call: php import.php http://server/jsonrpc.php apitoken trellokey trellotoken trelloboard userid). There is no jsonrpc.php in the project at github. I am new to this kind of stuff so I might be dumb, although I am into SW for a long time in the embedded world. There was an autoload include at the beginning of import.php, which (obviously) didn't work.
The code I use is attached. Is it possible to create a document how to use and adapt the script and the rpc lib to be used for kanboard located on a managed host?

Yours,

Ulrich Hauser-Ehninger

<?php

use JsonRPC\Client;

require_once(dirname(**FILE**) . '/util.php');
setTimezone("GMT");

/**------ FUNCTIONS ---------**/
if (!function_exists('json_last_error_msg')) {
    function json_last_error_msg() {
        static $errors = array(
            JSON_ERROR_NONE             => null,
            JSON_ERROR_DEPTH            => 'Maximum stack depth exceeded',
            JSON_ERROR_STATE_MISMATCH   => 'Underflow or the modes mismatch',
            JSON_ERROR_CTRL_CHAR        => 'Unexpected control character found',
            JSON_ERROR_SYNTAX           => 'Syntax error, malformed JSON',
            JSON_ERROR_UTF8             => 'Malformed UTF-8 characters, possibly incorrectly encoded'
        );
        $error = json_last_error();
        return array_key_exists($error, $errors) ? $errors[$error] : "Unknown error ({$error})";
    }
}
/**-------- END FUNCTIONS --------------**/

echo ("Passed line: " . **LINE** . PHP_EOL);

if (""==$_GET["server"])
{/\* assume we were NIT called via http*/
  echo ("I was called directly\n");
  if ($argc !== 6 && $argc !== 7) {
      echo 'Use this small tool to import your Trello JSON export into your kanboard, using it JSON-RPC interface.' . PHP_EOL;
      printf('Usage: php %s http://server/jsonrpc.php apitoken trellokey trellotoken trelloboard [userId]%s', $argv[0], PHP_EOL);
      echo 'To get the Trello key and token, login to Trello and go to https://trello.com/app-key'.PHP_EOL;
      echo 'The user id is optional. If you provide it, comments will be created with that userId.'.PHP_EOL;
      die;
  }

  $server = $argv[1];
  $token = $argv[2];
  $trellokey = $argv[3];
  $trellotoken = $argv[4];
  $trelloboard = $argv[5];
  $userId = null;
  if (isset($argv[6])) {
      $userId = $argv[6];
  }
}
else
{/_assume we were called via http"_/
  echo ("I was called via https\n");
  if (!isset ($_GET["server"])) die ("Parameter 'server' not present");
  $server = $_GET["server"];
  if (!isset ($_GET["token"])) die ("Parameter 'token' not present");
  $token = $_GET["token"];
  if (!isset ($_GET["trellokey"])) die ("Parameter 'trellokey' not present");
  $trellokey = $_GET["trellokey"];
  if (!isset ($_GET["trellotoken"])) die ("Parameter 'trellotoken' not present");
  $trellotoken = $_GET["trellotoken"];
  if (!isset ($_GET["trelloboard"])) die ("Parameter 'trelloboard' not present");
  $trelloboard = $_GET["trelloboard"];
  $userId = null;
  if (isset($_GET["userid"])) {
      $userId = $_GET["userid"];;
  }
}

echo ("I will import from: ". $trelloboard . PHP_EOL);

$fileName="https://trello.com/1/boards/".$trelloboard."?key=".$trellokey."&token=".$trellotoken;
echo ("reading file: ".$fileName. PHP_EOL);

$jsonString = file_get_contents("https://trello.com/1/boards/".$trelloboard."?key=".$trellokey."&token=".$trellotoken);

echo ("Passed line: " . **LINE** . PHP_EOL);

$trelloObj = json_decode($jsonString);

echo ("Passed line: " . **LINE** . PHP_EOL);

if (empty($trelloObj)) {
    printf($jsonString);
    printf('Unable to parse JSON response, is it valid? %s', json_last_error_msg());
    die(1);
}

echo ("Passed line: " . **LINE** . PHP_EOL);

//initialize the client
$client = new Client($server);
echo ("Passed line: " . **LINE** . PHP_EOL);
$client->authentication('jsonrpc', $token);

echo ("Passed line: " . **LINE** . PHP_EOL);

//verify that we can connect
$projects = null;
try {
    $projects = $client->getAllProjects();
} catch(RuntimeException $e) {
    $projects = null; //explicitly set it to null, to trigger an error
}

echo ("Passed line: " . **LINE** . PHP_EOL);

$users = $client->getAllUsers();
foreach ($users as $user) {
    if ($user['username'] == $userId || $userId == null) {
        $userId = $user['id'];
    }
}

echo ("Passed line: " . **LINE** . PHP_EOL);

if (!is_array($projects)) {
    echo 'Unable to fetch the list of projects, is the server url / token correct?' . PHP_EOL;
    die(1);
}

echo ("Passed line: " . **LINE** . PHP_EOL);

//variables
$trelloLists = array();
$trelloLabels = array(); //we will store all label names, but not add them immediately, only when used
$trelloAttachments = array();

//create the project
echo 'Creating project.' . PHP_EOL;
$projectId = $client->createProject($trelloObj->name);
$counter=0;
while (empty($projectId)) {
$projectId = $client->createProject($trelloObj->name.$counter++);
//  die("We could not create the project, perhaps it already exists?".PHP_EOL);
}

echo ("Passed line: " . **LINE** . PHP_EOL);

//remove the columns created by default
$columns = $client->getColumns($projectId);
foreach ($columns as $column) {
    $client->removeColumn($column['id']);
}

echo ("Passed line: " . **LINE** . PHP_EOL);

//set the public/private status of the project
if ($trelloObj->prefs->permissionLevel=="private") {
        echo "project is private".PHP_EOL;
    // $client->updateProject(array('id' => $projectId, 'is_public' => false));
}

echo ("Passed line: " . **LINE** . PHP_EOL);
# will only get lists that are not archived

$jsonString = file_get_contents("https://trello.com/1/boards/".$trelloboard."/lists?key=".$trellokey."&token=".$trellotoken);
$trelloObjLists = json_decode($jsonString);

echo ("Passed line: " . **LINE** . PHP_EOL);

//add the lists
echo 'Adding lists.' . PHP_EOL;
foreach ($trelloObjLists as $list) {
    if ($list->closed) {
        // ignore archived lists
        continue;
    }
    echo 'Creating list '.$list->name.PHP_EOL;
    $columnId = $client->addColumn($projectId, $list->name);
    $trelloLists[$list->id] = $columnId;

```
//add each card
echo 'Adding cards.' . PHP_EOL;
    $query="https://trello.com/1/lists/".$list->id."?key=".$trellokey."&token=".$trellotoken."&cards=open&card_fields=all&card_checklists=all&members=all&member_fields=all&membersInvited=all&checklists=all&organization=true&organization_fields=all&fields=all"; // &actions=commentCard,copyCommentCard&card_attachments=true";
    $jsonCards = file_get_contents($query);
$trelloObjCards = json_decode($jsonCards);

foreach ($trelloObjCards->cards as $card) {
    addCard($projectId, $columnId, $card);
}
```

}

echo 'All done!' . PHP_EOL;
die;

function addCard($projectId, $columnId, $card)
{
global $trellokey;
global $trellotoken;
global $trelloLabels;
global $client;
global $userId;

```
if ($card->closed) {
    // ignore archived cards
    return;
}

$dueDate = $card->due !== null ? date('Y-m-d', strtotime($card->due)) : null;

//Kanboard supports only one category, take the first one of the Trello labels
$colorId = null;
$categoryId = null;
if (count($card->labels) > 0) {
    $trelloLabel = $card->labels[0];
    $colorId = $trelloLabel->color;
    if (isset($trelloLabels[$trelloLabel->id])) {
        $categoryId = $trelloLabels[$trelloLabel->id];
    } else {
        $categoryId = $client->createCategory($projectId, $trelloLabel->name);
        $trelloLabels[$trelloLabel->id] = $categoryId;
    }
}

$params = array(
    'title' => $card->name,
    'project_id' => $projectId,
    'column_id' => $columnId
);
if ($card->desc !== null) {
    $params['description'] = $card->desc;
}
if ($dueDate !== null) {
    $params['date_due'] = $dueDate;
}
if ($colorId !== null) {
    $params['color_id'] = $colorId;
}
if ($categoryId !== null) {
    $params['category_id'] = $categoryId;
}
if ($userId !== null) {
    $params['owner_id'] = $userId;
}
$taskId = $client->createTask($params);

if ($card->badges->comments > 0) {
    $jsonString = 
        file_get_contents("https://trello.com/1/cards/".
            $card->shortLink."/actions?key=".$trellokey."&token=".$trellotoken."&filter=all");
    $cardDetails = json_decode($jsonString);
    addComments($cardDetails, $taskId);
}

if ($card->badges->checkItems > 0) {
    $jsonString = 
        file_get_contents("https://trello.com/1/cards/".
            $card->shortLink."/checklists?key=".$trellokey."&token=".$trellotoken);
    $cardDetails = json_decode($jsonString);
    addCheckItems($cardDetails, $taskId);
}

if ($card->badges->attachments > 0) {
    $jsonString = 
        file_get_contents("https://trello.com/1/cards/".
            $card->shortLink."/attachments?key=".$trellokey."&token=".$trellotoken);
    $cardDetails = json_decode($jsonString);
    addAttachments($card, $cardDetails, $taskId);
}
```

}

//download attachments
function addAttachments($card, $cardDetails, $taskId)
{
global $userId;
global $client;

```
foreach ($cardDetails as $attachment) {
    if ($attachment->isUpload) {
        $filename = $taskId . '_' . $attachment->name;
        printf('Downloading attachment for task %s to %s.%s', $card->name, $filename, PHP_EOL);
        $fpOut = fopen($filename, 'w');

        //Here is the file we are downloading, replace spaces with %20
        $ch = curl_init($attachment->url);

        curl_setopt($ch, CURLOPT_TIMEOUT, 50);

        //give curl the file pointer so that it can write to it
        curl_setopt($ch, CURLOPT_FILE, $fpOut);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

        $data = curl_exec($ch);//get curl response
        if ($data === false) {
            printf('Unable to download attachment: %s%s', curl_error($ch), PHP_EOL);
        }

        //done
        curl_close($ch);

        // add a comment about the file
        $text = "There was a file link in Trello, the file was called ".$attachment->name."\n\nSee local file ".$filename."\n\nThe original link is [".$attachment->name."](".$attachment->url.")";
        $client->createComment(array('task_id' => $taskId, 'user_id' => $userId, 'content' => $text));
    } else {
        // just an url, add a comment
        $text = $attachment->url;
        $client->createComment(array('task_id' => $taskId, 'user_id' => $userId, 'content' => $text));
    }
}
```

}

//add checklists as subtasks
function addCheckItems($cardDetails, $taskId)
{
global $userId;
global $client;

$statusTodo = 0;
$statusDone = 2;

```
foreach ($cardDetails as $checkList) {
    foreach ($checkList->checkItems as $checkItem) {
        $title = $checkList->name . ' - ' . $checkItem->name;
        $status = $checkItem->state === 'incomplete' ? $statusTodo : $statusDone;
        $client->createSubtask(array('task_id' => $taskId, 'title' => $title, 'status' => $status));
    }
}
```

}

function addComments($cardDetails, $taskId)
{
global $userId;
global $client;
    foreach ($cardDetails as $comment) {
        if ($comment->type === 'commentCard') {
            $text = $comment->data->text;
            $client->createComment(array('task_id' => $taskId, 'user_id' => $userId, 'content' => $text));
        }
    }
}

?>

**Comment by danships** [comment]
Hi,

You do not have to have this script installed on the same host as the kanboard deployment. You can run it on your own computer and have it connect to the site URL. But it is nice to see you found your own way to work around it.

With regards to the missing JSONRPC client, did you execute `composer install` as explained in the readme? (https://github.com/matueranet/kanboard-import-trello#installation) It seems to me you missed that step. For information on composer, see https://getcomposer.org
